name: Zip and Upload Artifact

on: 
  push:
    branches:
      - main  # You can specify the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Zip repository
      run: |
        rm -Rf _config.yml
        rm -Rf BIOSUpdate
        rm -Rf Displays
        rm -Rf HotPatch
        rm -Rf Opencore-Debug
        rm -Rf BIOSUpdate
        rm -Rf TOOLS
        rm -Rf "IORegistry.ioreg"
        rm -Rf README.md
      
        zip -r repository.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: repository-zip
        path: repository.zip

    - name: Upload to Release
      uses: actions/upload-artifact@v3
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        name: repository-zip
        path: repository.zip
