name: Zip and Upload Artifact

on: 
  push:
    branches:
      - main  # You can specify the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Zip hp-DA1023nia-macOS
      run: |
        rm -Rf _config.yml
        rm -Rf BIOSUpdate
        rm -Rf Displays
        rm -Rf HotPatch
        rm -Rf Opencore-Debug
        rm -Rf BIOSUpdate
        rm -Rf TOOLS
        rm -Rf "IORegistry.ioreg"
        rm -Rf README.md
      
        zip -r hp-DA1023nia-macOS.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hp-DA1023nia-macOS-zip
        path: hp-DA1023nia-macOS.zip

    - name: Upload build
      uses: svenstaro/upload-release-action@2.9.0
      if: github.event_name != 'pull_request'
      with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         file: ./*.zip
         tag: ${{ github.ref }}
         release_name: EFI hp-DA1023nia-macOS Hackintosh
         body: ${{ github.event_name != 'release' && github.event.head_commit.message || '' }}
         file_glob: true
         overwrite: true
